//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public int IdAction { get; set; }
        public string LibelleAction { get; set; }
        public Nullable<System.DateTime> HeureAction { get; set; }
        public Nullable<int> IdConnexion { get; set; }
    
        public virtual Connexion Connexion { get; set; }
    }
}
