//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affectation
    {
        public int IdAffectation { get; set; }
        public Nullable<int> IdMission { get; set; }
        public Nullable<int> IdVehicule { get; set; }
        public Nullable<int> IdConducteur { get; set; }
        public Nullable<System.DateTime> DateAffectation { get; set; }
    
        public virtual Conducteur Conducteur { get; set; }
        public virtual Mission Mission { get; set; }
        public virtual Vehicule Vehicule { get; set; }
    }
}
