//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connexion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Connexion()
        {
            this.Action = new HashSet<Action>();
        }
    
        public int IdConnexion { get; set; }
        public Nullable<System.DateTime> DebutConnexion { get; set; }
        public Nullable<System.DateTime> FinConnexion { get; set; }
        public string SystemeOS { get; set; }
        public string Navigateur { get; set; }
        public string AdresseIP { get; set; }
        public string AdresseMac { get; set; }
        public string Machine { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<bool> Supprimer { get; set; }
        public Nullable<System.DateTime> DateSupprimer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action> Action { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
