//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailAssurance
    {
        public int IdDetailAssurance { get; set; }
        public Nullable<int> IdAssurance { get; set; }
        public Nullable<int> IdVehicule { get; set; }
        public Nullable<System.DateTime> DataDebutCouverture { get; set; }
        public Nullable<System.DateTime> DateFinCouverture { get; set; }
    
        public virtual Assurance Assurance { get; set; }
        public virtual Vehicule Vehicule { get; set; }
    }
}
