//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MecaIntervention
    {
        public int IdTechIntervention { get; set; }
        public Nullable<System.DateTime> DateIntervention { get; set; }
        public Nullable<int> IdMecanicien { get; set; }
        public Nullable<int> IdIntervention { get; set; }
    
        public virtual Intervention Intervention { get; set; }
        public virtual Mecanicien Mecanicien { get; set; }
    }
}
