//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mecanicien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mecanicien()
        {
            this.EntreeCarburant = new HashSet<EntreeCarburant>();
            this.EntreeHuile = new HashSet<EntreeHuile>();
            this.MecaIntervention = new HashSet<MecaIntervention>();
            this.SortieCarburant = new HashSet<SortieCarburant>();
            this.SortieHuile = new HashSet<SortieHuile>();
        }
    
        public int IdMecanicien { get; set; }
        public string NumCNIMecanicien { get; set; }
        public string NomMecanicien { get; set; }
        public string PrenomMecanicien { get; set; }
        public Nullable<System.DateTime> DateNaissanceMecanicien { get; set; }
        public string LieuxNaissanceMecanicien { get; set; }
        public string SexeMecanicien { get; set; }
        public string AdresseMecanicien { get; set; }
        public string TelMecanicien { get; set; }
        public string EmailMecanicien { get; set; }
        public Nullable<System.DateTime> DateEmbaucheMecanicien { get; set; }
        public Nullable<bool> EnActivite { get; set; }
        public Nullable<System.DateTime> DateDesactivation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntreeCarburant> EntreeCarburant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntreeHuile> EntreeHuile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MecaIntervention> MecaIntervention { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SortieCarburant> SortieCarburant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SortieHuile> SortieHuile { get; set; }
    }
}
