//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mission()
        {
            this.Affectation = new HashSet<Affectation>();
        }
    
        public int IdMission { get; set; }
        public string LibelleMission { get; set; }
        public Nullable<System.DateTime> DateDebutMission { get; set; }
        public Nullable<System.DateTime> DateFinMission { get; set; }
        public Nullable<int> IdCategorieMission { get; set; }
        public Nullable<int> IdTypeMission { get; set; }
        public Nullable<bool> Cloturer { get; set; }
        public Nullable<System.DateTime> DateCloturer { get; set; }
        public Nullable<bool> Supprimer { get; set; }
        public Nullable<System.DateTime> DateSupprimer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Affectation> Affectation { get; set; }
        public virtual CategorieMission CategorieMission { get; set; }
        public virtual TypeMission TypeMission { get; set; }
    }
}
