//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SortieHuile
    {
        public int IdSortieHuile { get; set; }
        public Nullable<double> VolumeSortieHuile { get; set; }
        public Nullable<System.DateTime> DateSortieHuile { get; set; }
        public Nullable<int> IdVehicule { get; set; }
        public Nullable<int> IdHuile { get; set; }
        public Nullable<int> IdMecanicien { get; set; }
        public Nullable<bool> Supprimer { get; set; }
        public Nullable<System.DateTime> DateSupprime { get; set; }
    
        public virtual Huile Huile { get; set; }
        public virtual Mecanicien Mecanicien { get; set; }
        public virtual Vehicule Vehicule { get; set; }
    }
}
