//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SortieCarburant
    {
        public int IdSortieCarburant { get; set; }
        public Nullable<double> VolumeSortieCarburant { get; set; }
        public Nullable<System.DateTime> DateSortieCarburant { get; set; }
        public Nullable<int> IdVehicule { get; set; }
        public Nullable<int> IdCarburant { get; set; }
        public Nullable<int> IdMecanicien { get; set; }
        public Nullable<bool> Supprimer { get; set; }
        public Nullable<System.DateTime> DateSupprime { get; set; }
    
        public virtual Carburant Carburant { get; set; }
        public virtual Mecanicien Mecanicien { get; set; }
        public virtual Vehicule Vehicule { get; set; }
    }
}
