//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilisateur()
        {
            this.Connexion = new HashSet<Connexion>();
        }
    
        public int IdUser { get; set; }
        public string NumCNIUser { get; set; }
        public string NomUser { get; set; }
        public string PrenomUser { get; set; }
        public Nullable<System.DateTime> DateNaissanceUser { get; set; }
        public string LieuxNaissanceUser { get; set; }
        public string SexeUser { get; set; }
        public string AdresseUser { get; set; }
        public string TelUser { get; set; }
        public string EmailUser { get; set; }
        public Nullable<System.DateTime> DateEmbaucheUser { get; set; }
        public Nullable<System.DateTime> DateCreationCompteUser { get; set; }
        public string Identifiant { get; set; }
        public string MotDePasse { get; set; }
        public Nullable<System.DateTime> DateModificationPass { get; set; }
        public Nullable<int> Tentative { get; set; }
        public Nullable<bool> EstConnecte { get; set; }
        public Nullable<bool> EnActivite { get; set; }
        public Nullable<System.DateTime> DateDesactivation { get; set; }
        public Nullable<int> IdProfil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Connexion> Connexion { get; set; }
        public virtual Profil Profil { get; set; }
    }
}
