//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicule()
        {
            this.Affectation = new HashSet<Affectation>();
            this.DetailAssurance = new HashSet<DetailAssurance>();
            this.HistoriqueAspect = new HashSet<HistoriqueAspect>();
            this.Intervention = new HashSet<Intervention>();
            this.SortieCarburant = new HashSet<SortieCarburant>();
            this.SortieHuile = new HashSet<SortieHuile>();
        }
    
        public int IdVehicule { get; set; }
        public string NomVehicule { get; set; }
        public string NumChassis { get; set; }
        public string Immatriculation { get; set; }
        public Nullable<System.DateTime> DateAcquisition { get; set; }
        public Nullable<System.DateTime> DateExpireGarantie { get; set; }
        public Nullable<int> IdFournisseur { get; set; }
        public Nullable<int> IdTypeCarb { get; set; }
        public Nullable<int> IdMarque { get; set; }
        public Nullable<int> IdType { get; set; }
        public Nullable<bool> EnActivite { get; set; }
        public Nullable<bool> EnMission { get; set; }
        public Nullable<System.DateTime> DateDesactivation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Affectation> Affectation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailAssurance> DetailAssurance { get; set; }
        public virtual Fournisseur Fournisseur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoriqueAspect> HistoriqueAspect { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Intervention> Intervention { get; set; }
        public virtual MarqueVehicule MarqueVehicule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SortieCarburant> SortieCarburant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SortieHuile> SortieHuile { get; set; }
        public virtual TypeCarburant TypeCarburant { get; set; }
        public virtual TypeVehicule TypeVehicule { get; set; }
    }
}
